#pragma once
#include "type.h"

enum SessionType : uint8_t
{
	SESSION_NEW=16, 
	SESSION_RECONNECTING=18
};

enum ClientVersion : uint8_t
{
	CLIENT_VERSION_LOW_MEMORY=0,
	CLIENT_VERSION_HIGH_MEMORY
};
enum PlayerStatus : uint8_t
{
	PLAYER_STATUS_NORMAL=0,
	PLAYER_STATUS_MODERATOR,
	PLAYER_STATUS_ADMIN
};

enum RequestType : uint8_t
{
	REQUEST_TYPE_LOGIN_REQUEST = 14,
	REQUEST_TYPE_UPDATE=15,
	REQUEST_TYPE_NEW_CONNECTION_LOGIN=16,
	REQUEST_TYPE_RECONNECTION_LOGIN = 18,
};


enum ResponseCode : int8_t
{
	RESPONSE_CODE_WAIT=-1,
	RESPONSE_CODE_EXCHANGE_SESSION_KEYS,
	RESPONSE_CODE_WAIT_AND_TRY_AGAIN,
	RESPONSE_CODE_SUCCESSFUL_LOGIN,
	RESPONSE_CODE_INVALID_USER_NAME_PASSWORD,
	RESPONSE_CODE_ACCOUNT_DISABLED,
	RESPONSE_CODE_ACCOUNT_READY_TO_LOGIN,
	RESPONSE_CODE_PAGE_RELOAD,
	RESPONSE_CODE_WORLD_FULL,
	RESPONSE_CODE_UNABLE_TO_CONNECT,
	RESPONSE_CODE_LOGIN_LIMIT_EXCEED,
};